// Mocks generated by Mockito 5.4.6 from annotations
// in klump_checkout/test/klump_checkout_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i4;
import 'package:klump_checkout/src/domain/usecases/account_credentials.dart'
    as _i3;
import 'package:klump_checkout/src/src.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInitiateTransactionUsecase_0 extends _i1.SmartFake
    implements _i2.InitiateTransactionUsecase {
  _FakeInitiateTransactionUsecase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountValidationUsecase_1 extends _i1.SmartFake
    implements _i2.AccountValidationUsecase {
  _FakeAccountValidationUsecase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyOTPUsecase_2 extends _i1.SmartFake
    implements _i2.VerifyOTPUsecase {
  _FakeVerifyOTPUsecase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetBankTCUsecase_3 extends _i1.SmartFake
    implements _i2.GetBankTCUsecase {
  _FakeGetBankTCUsecase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRepaymentDetailsUsecase_4 extends _i1.SmartFake
    implements _i2.GetRepaymentDetailsUsecase {
  _FakeGetRepaymentDetailsUsecase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLoanStatusUsecase_5 extends _i1.SmartFake
    implements _i2.GetLoanStatusUsecase {
  _FakeGetLoanStatusUsecase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPartnerInsurersUsecase_6 extends _i1.SmartFake
    implements _i2.GetPartnerInsurersUsecase {
  _FakeGetPartnerInsurersUsecase_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountCredentialsUsecase_7 extends _i1.SmartFake
    implements _i3.AccountCredentialsUsecase {
  _FakeAccountCredentialsUsecase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLoanPartnersUsecase_8 extends _i1.SmartFake
    implements _i2.GetLoanPartnersUsecase {
  _FakeGetLoanPartnersUsecase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePartnersUsecase_9 extends _i1.SmartFake
    implements _i2.PartnersUsecase {
  _FakePartnersUsecase_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePageController_10 extends _i1.SmartFake
    implements _i4.PageController {
  _FakePageController_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KCChangeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockKCChangeNotifier extends _i1.Mock implements _i2.KCChangeNotifier {
  MockKCChangeNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InitiateTransactionUsecase get initiateTransactionUsecase =>
      (super.noSuchMethod(
        Invocation.getter(#initiateTransactionUsecase),
        returnValue: _FakeInitiateTransactionUsecase_0(
          this,
          Invocation.getter(#initiateTransactionUsecase),
        ),
      ) as _i2.InitiateTransactionUsecase);

  @override
  _i2.AccountValidationUsecase get accountValidationUsecase =>
      (super.noSuchMethod(
        Invocation.getter(#accountValidationUsecase),
        returnValue: _FakeAccountValidationUsecase_1(
          this,
          Invocation.getter(#accountValidationUsecase),
        ),
      ) as _i2.AccountValidationUsecase);

  @override
  _i2.VerifyOTPUsecase get verifyOTPUsecase => (super.noSuchMethod(
        Invocation.getter(#verifyOTPUsecase),
        returnValue: _FakeVerifyOTPUsecase_2(
          this,
          Invocation.getter(#verifyOTPUsecase),
        ),
      ) as _i2.VerifyOTPUsecase);

  @override
  _i2.GetBankTCUsecase get getBankTCUsecase => (super.noSuchMethod(
        Invocation.getter(#getBankTCUsecase),
        returnValue: _FakeGetBankTCUsecase_3(
          this,
          Invocation.getter(#getBankTCUsecase),
        ),
      ) as _i2.GetBankTCUsecase);

  @override
  _i2.GetRepaymentDetailsUsecase get getRepaymentDetailsUsecase =>
      (super.noSuchMethod(
        Invocation.getter(#getRepaymentDetailsUsecase),
        returnValue: _FakeGetRepaymentDetailsUsecase_4(
          this,
          Invocation.getter(#getRepaymentDetailsUsecase),
        ),
      ) as _i2.GetRepaymentDetailsUsecase);

  @override
  _i2.GetLoanStatusUsecase get getLoanStatusUsecase => (super.noSuchMethod(
        Invocation.getter(#getLoanStatusUsecase),
        returnValue: _FakeGetLoanStatusUsecase_5(
          this,
          Invocation.getter(#getLoanStatusUsecase),
        ),
      ) as _i2.GetLoanStatusUsecase);

  @override
  _i2.GetPartnerInsurersUsecase get getPartnerInsurersUsecase =>
      (super.noSuchMethod(
        Invocation.getter(#getPartnerInsurersUsecase),
        returnValue: _FakeGetPartnerInsurersUsecase_6(
          this,
          Invocation.getter(#getPartnerInsurersUsecase),
        ),
      ) as _i2.GetPartnerInsurersUsecase);

  @override
  _i3.AccountCredentialsUsecase get accountCredentialsUsecase =>
      (super.noSuchMethod(
        Invocation.getter(#accountCredentialsUsecase),
        returnValue: _FakeAccountCredentialsUsecase_7(
          this,
          Invocation.getter(#accountCredentialsUsecase),
        ),
      ) as _i3.AccountCredentialsUsecase);

  @override
  _i2.GetLoanPartnersUsecase get getLoanPartnersUsecase => (super.noSuchMethod(
        Invocation.getter(#getLoanPartnersUsecase),
        returnValue: _FakeGetLoanPartnersUsecase_8(
          this,
          Invocation.getter(#getLoanPartnersUsecase),
        ),
      ) as _i2.GetLoanPartnersUsecase);

  @override
  _i2.PartnersUsecase get partnersUsecase => (super.noSuchMethod(
        Invocation.getter(#partnersUsecase),
        returnValue: _FakePartnersUsecase_9(
          this,
          Invocation.getter(#partnersUsecase),
        ),
      ) as _i2.PartnersUsecase);

  @override
  bool get isBusy => (super.noSuchMethod(
        Invocation.getter(#isBusy),
        returnValue: false,
      ) as bool);

  @override
  int get currentPage => (super.noSuchMethod(
        Invocation.getter(#currentPage),
        returnValue: 0,
      ) as int);

  @override
  _i4.PageController get pageController => (super.noSuchMethod(
        Invocation.getter(#pageController),
        returnValue: _FakePageController_10(
          this,
          Invocation.getter(#pageController),
        ),
      ) as _i4.PageController);

  @override
  double get totalAmount => (super.noSuchMethod(
        Invocation.getter(#totalAmount),
        returnValue: 0.0,
      ) as double);

  @override
  String get tranxReference => (super.noSuchMethod(
        Invocation.getter(#tranxReference),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#tranxReference),
        ),
      ) as String);

  @override
  List<Map<String, dynamic>> get productDetails => (super.noSuchMethod(
        Invocation.getter(#productDetails),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  set initiateTransactionUsecase(
          _i2.InitiateTransactionUsecase? _initiateTransactionUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #initiateTransactionUsecase,
          _initiateTransactionUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set accountValidationUsecase(
          _i2.AccountValidationUsecase? _accountValidationUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #accountValidationUsecase,
          _accountValidationUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set verifyOTPUsecase(_i2.VerifyOTPUsecase? _verifyOTPUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #verifyOTPUsecase,
          _verifyOTPUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set getBankTCUsecase(_i2.GetBankTCUsecase? _getBankTCUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #getBankTCUsecase,
          _getBankTCUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set getRepaymentDetailsUsecase(
          _i2.GetRepaymentDetailsUsecase? _getRepaymentDetailsUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #getRepaymentDetailsUsecase,
          _getRepaymentDetailsUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set getLoanStatusUsecase(_i2.GetLoanStatusUsecase? _getLoanStatusUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #getLoanStatusUsecase,
          _getLoanStatusUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set getPartnerInsurersUsecase(
          _i2.GetPartnerInsurersUsecase? _getPartnerInsurersUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #getPartnerInsurersUsecase,
          _getPartnerInsurersUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set accountCredentialsUsecase(
          _i3.AccountCredentialsUsecase? _accountCredentialsUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #accountCredentialsUsecase,
          _accountCredentialsUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set getLoanPartnersUsecase(
          _i2.GetLoanPartnersUsecase? _getLoanPartnersUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #getLoanPartnersUsecase,
          _getLoanPartnersUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set partnersUsecase(_i2.PartnersUsecase? _partnersUsecase) =>
      super.noSuchMethod(
        Invocation.setter(
          #partnersUsecase,
          _partnersUsecase,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void nextPage() => super.noSuchMethod(
        Invocation.method(
          #nextPage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void prevPage() => super.noSuchMethod(
        Invocation.method(
          #prevPage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTransactionData(_i2.KlumpCheckoutData? data) => super.noSuchMethod(
        Invocation.method(
          #setTransactionData,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBankFlow(_i2.Partner? bank) => super.noSuchMethod(
        Invocation.method(
          #setBankFlow,
          [bank],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectBank(Map<String, dynamic>? bank) => super.noSuchMethod(
        Invocation.method(
          #selectBank,
          [bank],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectDocumentType(String? type) => super.noSuchMethod(
        Invocation.method(
          #selectDocumentType,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void storeNextStepData(_i2.KCAPIResponse? data) => super.noSuchMethod(
        Invocation.method(
          #storeNextStepData,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> initiateTransaction({
    required String? email,
    required String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateTransaction,
          [],
          {
            #email: email,
            #phone: phone,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> getLoanPartners() => (super.noSuchMethod(
        Invocation.method(
          #getLoanPartners,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> validateAccount({
    String? accountNumber,
    String? phoneNumber,
    String? firstName,
    String? email,
    String? password,
    String? username,
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateAccount,
          [],
          {
            #accountNumber: accountNumber,
            #phoneNumber: phoneNumber,
            #firstName: firstName,
            #email: email,
            #password: password,
            #username: username,
            #pin: pin,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> resendAccountOTP() => (super.noSuchMethod(
        Invocation.method(
          #resendAccountOTP,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> verifyOTP(
    String? otp,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [
            otp,
            password,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createLoan() => (super.noSuchMethod(
        Invocation.method(
          #createLoan,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.DisbursementStatusResponse?> getLoanStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLoanStatus,
          [],
        ),
        returnValue: _i6.Future<_i2.DisbursementStatusResponse?>.value(),
      ) as _i6.Future<_i2.DisbursementStatusResponse?>);

  @override
  void skipLoanStatus() => super.noSuchMethod(
        Invocation.method(
          #skipLoanStatus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> getPartnerInsurer() => (super.noSuchMethod(
        Invocation.method(
          #getPartnerInsurer,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addAccountCredentials(
    String? email,
    String? password,
    DateTime? dob,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAccountCredentials,
          [
            email,
            password,
            dob,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> acceptRepaymentTerms({String? reference}) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptRepaymentTerms,
          [],
          {#reference: reference},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> acceptTermsAndCondition({String? reference}) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptTermsAndCondition,
          [],
          {#reference: reference},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> wemaRedirect() => (super.noSuchMethod(
        Invocation.method(
          #wemaRedirect,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> acceptRequirement() => (super.noSuchMethod(
        Invocation.method(
          #acceptRequirement,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> newAccount() => (super.noSuchMethod(
        Invocation.method(
          #newAccount,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> linkWithMono(_i4.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithMono,
          [context],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> linkExistingMono(
    _i4.BuildContext? context, {
    required String? monoAuthCode,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkExistingMono,
          [context],
          {
            #monoAuthCode: monoAuthCode,
            #token: token,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> bioData({
    required String? email,
    required String? firstname,
    required String? lastname,
    required DateTime? dob,
    required String? password,
    required double? amount,
    required String? apartment,
    required String? address,
    required String? city,
    required String? state,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bioData,
          [],
          {
            #email: email,
            #firstname: firstname,
            #lastname: lastname,
            #dob: dob,
            #password: password,
            #amount: amount,
            #apartment: apartment,
            #address: address,
            #city: city,
            #state: state,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> partnerKYC({
    required String? nin,
    required String? maritalStatus,
    required String? residentialStatus,
    required String? address,
    required String? landmark,
    required String? city,
    required String? state,
    required DateTime? dateMovedIn,
    required String? employmentStatus,
    required String? companyName,
    required String? companyIndustry,
    required String? companyAddress,
    required DateTime? companyStartDate,
    required String? monthlyIncome,
    required String? education,
    required String? nextOfKinName,
    required String? nextOfKinRetionship,
    required String? nextOfKinPhone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #partnerKYC,
          [],
          {
            #nin: nin,
            #maritalStatus: maritalStatus,
            #residentialStatus: residentialStatus,
            #address: address,
            #landmark: landmark,
            #city: city,
            #state: state,
            #dateMovedIn: dateMovedIn,
            #employmentStatus: employmentStatus,
            #companyName: companyName,
            #companyIndustry: companyIndustry,
            #companyAddress: companyAddress,
            #companyStartDate: companyStartDate,
            #monthlyIncome: monthlyIncome,
            #education: education,
            #nextOfKinName: nextOfKinName,
            #nextOfKinRetionship: nextOfKinRetionship,
            #nextOfKinPhone: nextOfKinPhone,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> getRepaymentDetails({
    required String? installments,
    required int? repaymentDay,
    required _i2.PartnerInsurer? insurer,
    required double? downpaymentAmount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRepaymentDetails,
          [],
          {
            #installments: installments,
            #repaymentDay: repaymentDay,
            #insurer: insurer,
            #downpaymentAmount: downpaymentAmount,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> uploadDocument({
    required String? idNumber,
    required _i7.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadDocument,
          [],
          {
            #idNumber: idNumber,
            #file: file,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addressVerify({required _i7.File? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addressVerify,
          [],
          {#file: file},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> validateSelfie({required String? filePath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateSelfie,
          [],
          {#filePath: filePath},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> verifyAccountNumber({
    required String? accountNumber,
    required Map<String, dynamic>? bank,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyAccountNumber,
          [],
          {
            #accountNumber: accountNumber,
            #bank: bank,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> enterBVN({required String? bvn}) => (super.noSuchMethod(
        Invocation.method(
          #enterBVN,
          [],
          {#bvn: bvn},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendBVNOTP({
    required String? bvn,
    required Map<String, dynamic>? contact,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendBVNOTP,
          [],
          {
            #bvn: bvn,
            #contact: contact,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> verifyBVN({required String? otp}) => (super.noSuchMethod(
        Invocation.method(
          #verifyBVN,
          [],
          {#otp: otp},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createPhoneNumber({required String? phoneNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPhoneNumber,
          [],
          {#phoneNumber: phoneNumber},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> verifyPhoneOTP({required String? otp}) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneOTP,
          [],
          {#otp: otp},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resendPhoneOTP() => (super.noSuchMethod(
        Invocation.method(
          #resendPhoneOTP,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void selectBankSubmitted() => super.noSuchMethod(
        Invocation.method(
          #selectBankSubmitted,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
