name: klump_checkout
description:  A Flutter plugin for payment checkout on Klump gateway. Completely supports Android and iOS.
version: 1.0.3
homepage: https://github.com/Klump-Inc/flutter_plugin

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_webview_pro: ^3.0.1+4
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.klump.inc.klump_checkout
        pluginClass: KlumpCheckoutPlugin
      ios:
        pluginClass: KlumpCheckoutPlugin