name: klump_checkout
description:  A Flutter plugin for payment checkout on Klump gateway. Completely supports Android and iOS.
version: 1.0.8
homepage: https://github.com/Klump-Inc/flutter_plugin

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.1.0
  provider: ^6.0.5
  flutter_svg: ^2.0.1
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  dio: ^5.0.1
  internet_connection_checker: ^0.0.1+4
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.1.0
  flutter_html:  ^3.0.0-alpha.6
  oktoast: ^3.3.1
  url_launcher: ^6.1.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.11
  build_runner: ^2.2.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Heavy.ttf
        - asset: assets/fonts/avenir/Avenir-Black.ttf
        - asset: assets/fonts/avenir/Avenir-Book.ttf
        - asset: assets/fonts/avenir/Avenir-Regular.ttf
        - asset: assets/fonts/avenir/Avenir-Light.ttf
  plugin:
    platforms:
      android:
        package: com.klump.inc.klump_checkout
        pluginClass: KlumpCheckoutPlugin
      ios:
        pluginClass: KlumpCheckoutPlugin
  
  