name: Test Code
on:
  pull_request: 
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.11'
        channel: 'stable'
        architecture: x64
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test